name: ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  policy:
    uses: arres_devops/.github/workflows/policy-ci.yml@main
    with:
      project_type: python_service
      docker_image_name: mock_api
      artifact_name: mock_api
      run_integration: true
