name: ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  policy:
    uses: hzr3d/arres_devops/.github/workflows/policy-ci.yml@feat/add-multi-repo-support
    with:
      project_type: python_service
      docker_image_name: mock_api
      artifact_name: mock_api
      run_integration: true
      with_mock_lib: true
